[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
agent-core = { version = "0.1.0", path = "../core" }
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9.34"
